package bean;
// Generated 13/10/2025 08:01:10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GaaClientes generated by hbm2java
 */
@Entity
@Table(name="gaa_clientes"
    ,catalog="db_gabriel_amaral"
)
public class GaaClientes  implements java.io.Serializable {


     private int gaaIdClientes;
     private String gaaNome;
     private String gaaEmail;
     private String gaaTelefone;
     private String gaaEndereco;
     private String gaaCidade;
     private String gaaEstado;
     private String gaaCep;
     private String gaaCpf;
     private Date gaaDataNascimento;
     private String gaaGenero;
     private String gaaTrabalhoFormal;
     private String gaaProfissao;
     private String gaaAtivo;
     private Date gaaDataCadastro;
     private Set gaaVendases = new HashSet(0);

    public GaaClientes() {
    }

	
    public GaaClientes(int gaaIdClientes, String gaaNome, String gaaEmail, String gaaTelefone, String gaaEndereco, String gaaCidade, String gaaEstado, String gaaCep, String gaaCpf, String gaaGenero, String gaaTrabalhoFormal, String gaaProfissao, String gaaAtivo) {
        this.gaaIdClientes = gaaIdClientes;
        this.gaaNome = gaaNome;
        this.gaaEmail = gaaEmail;
        this.gaaTelefone = gaaTelefone;
        this.gaaEndereco = gaaEndereco;
        this.gaaCidade = gaaCidade;
        this.gaaEstado = gaaEstado;
        this.gaaCep = gaaCep;
        this.gaaCpf = gaaCpf;
        this.gaaGenero = gaaGenero;
        this.gaaTrabalhoFormal = gaaTrabalhoFormal;
        this.gaaProfissao = gaaProfissao;
        this.gaaAtivo = gaaAtivo;
    }
    public GaaClientes(int gaaIdClientes, String gaaNome, String gaaEmail, String gaaTelefone, String gaaEndereco, String gaaCidade, String gaaEstado, String gaaCep, String gaaCpf, Date gaaDataNascimento, String gaaGenero, String gaaTrabalhoFormal, String gaaProfissao, String gaaAtivo, Date gaaDataCadastro, Set gaaVendases) {
       this.gaaIdClientes = gaaIdClientes;
       this.gaaNome = gaaNome;
       this.gaaEmail = gaaEmail;
       this.gaaTelefone = gaaTelefone;
       this.gaaEndereco = gaaEndereco;
       this.gaaCidade = gaaCidade;
       this.gaaEstado = gaaEstado;
       this.gaaCep = gaaCep;
       this.gaaCpf = gaaCpf;
       this.gaaDataNascimento = gaaDataNascimento;
       this.gaaGenero = gaaGenero;
       this.gaaTrabalhoFormal = gaaTrabalhoFormal;
       this.gaaProfissao = gaaProfissao;
       this.gaaAtivo = gaaAtivo;
       this.gaaDataCadastro = gaaDataCadastro;
       this.gaaVendases = gaaVendases;
    }
   
     @Id 

    
    @Column(name="gaa_idClientes", unique=true, nullable=false)
    public int getGaaIdClientes() {
        return this.gaaIdClientes;
    }
    
    public void setGaaIdClientes(int gaaIdClientes) {
        this.gaaIdClientes = gaaIdClientes;
    }

    
    @Column(name="gaa_nome", nullable=false, length=100)
    public String getGaaNome() {
        return this.gaaNome;
    }
    
    public void setGaaNome(String gaaNome) {
        this.gaaNome = gaaNome;
    }

    
    @Column(name="gaa_email", nullable=false, length=100)
    public String getGaaEmail() {
        return this.gaaEmail;
    }
    
    public void setGaaEmail(String gaaEmail) {
        this.gaaEmail = gaaEmail;
    }

    
    @Column(name="gaa_telefone", nullable=false, length=15)
    public String getGaaTelefone() {
        return this.gaaTelefone;
    }
    
    public void setGaaTelefone(String gaaTelefone) {
        this.gaaTelefone = gaaTelefone;
    }

    
    @Column(name="gaa_endereco", nullable=false, length=75)
    public String getGaaEndereco() {
        return this.gaaEndereco;
    }
    
    public void setGaaEndereco(String gaaEndereco) {
        this.gaaEndereco = gaaEndereco;
    }

    
    @Column(name="gaa_cidade", nullable=false, length=50)
    public String getGaaCidade() {
        return this.gaaCidade;
    }
    
    public void setGaaCidade(String gaaCidade) {
        this.gaaCidade = gaaCidade;
    }

    
    @Column(name="gaa_estado", nullable=false, length=50)
    public String getGaaEstado() {
        return this.gaaEstado;
    }
    
    public void setGaaEstado(String gaaEstado) {
        this.gaaEstado = gaaEstado;
    }

    
    @Column(name="gaa_cep", nullable=false, length=9)
    public String getGaaCep() {
        return this.gaaCep;
    }
    
    public void setGaaCep(String gaaCep) {
        this.gaaCep = gaaCep;
    }

    
    @Column(name="gaa_cpf", nullable=false, length=11)
    public String getGaaCpf() {
        return this.gaaCpf;
    }
    
    public void setGaaCpf(String gaaCpf) {
        this.gaaCpf = gaaCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Gaa_dataNascimento", length=10)
    public Date getGaaDataNascimento() {
        return this.gaaDataNascimento;
    }
    
    public void setGaaDataNascimento(Date gaaDataNascimento) {
        this.gaaDataNascimento = gaaDataNascimento;
    }

    
    @Column(name="gaa_genero", nullable=false, length=10)
    public String getGaaGenero() {
        return this.gaaGenero;
    }
    
    public void setGaaGenero(String gaaGenero) {
        this.gaaGenero = gaaGenero;
    }

    
    @Column(name="gaa_trabalhoFormal", nullable=false, length=10)
    public String getGaaTrabalhoFormal() {
        return this.gaaTrabalhoFormal;
    }
    
    public void setGaaTrabalhoFormal(String gaaTrabalhoFormal) {
        this.gaaTrabalhoFormal = gaaTrabalhoFormal;
    }

    
    @Column(name="gaa_profissao", nullable=false, length=30)
    public String getGaaProfissao() {
        return this.gaaProfissao;
    }
    
    public void setGaaProfissao(String gaaProfissao) {
        this.gaaProfissao = gaaProfissao;
    }

    
    @Column(name="gaa_ativo", nullable=false, length=1)
    public String getGaaAtivo() {
        return this.gaaAtivo;
    }
    
    public void setGaaAtivo(String gaaAtivo) {
        this.gaaAtivo = gaaAtivo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="Gaa_dataCadastro", length=10)
    public Date getGaaDataCadastro() {
        return this.gaaDataCadastro;
    }
    
    public void setGaaDataCadastro(Date gaaDataCadastro) {
        this.gaaDataCadastro = gaaDataCadastro;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gaaClientes")
    public Set getGaaVendases() {
        return this.gaaVendases;
    }
    
    public void setGaaVendases(Set gaaVendases) {
        this.gaaVendases = gaaVendases;
    }




}


