package bean;
// Generated 13/10/2025 08:01:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * GaaProdutos generated by hbm2java
 */
@Entity
@Table(name="gaa_produtos"
    ,catalog="db_gabriel_amaral"
)
public class GaaProdutos  implements java.io.Serializable {


     private int gaaIdProdutos;
     private String gaaNome;
     private String gaaDescricao;
     private BigDecimal gaaPreco;
     private String gaaMarca;
     private String gaaMaterial;
     private String gaaAtivo;
     private Set gaaVendasProdutoses = new HashSet(0);

    public GaaProdutos() {
    }

	
    public GaaProdutos(int gaaIdProdutos, String gaaNome, String gaaDescricao, BigDecimal gaaPreco, String gaaMarca, String gaaMaterial, String gaaAtivo) {
        this.gaaIdProdutos = gaaIdProdutos;
        this.gaaNome = gaaNome;
        this.gaaDescricao = gaaDescricao;
        this.gaaPreco = gaaPreco;
        this.gaaMarca = gaaMarca;
        this.gaaMaterial = gaaMaterial;
        this.gaaAtivo = gaaAtivo;
    }
    public GaaProdutos(int gaaIdProdutos, String gaaNome, String gaaDescricao, BigDecimal gaaPreco, String gaaMarca, String gaaMaterial, String gaaAtivo, Set gaaVendasProdutoses) {
       this.gaaIdProdutos = gaaIdProdutos;
       this.gaaNome = gaaNome;
       this.gaaDescricao = gaaDescricao;
       this.gaaPreco = gaaPreco;
       this.gaaMarca = gaaMarca;
       this.gaaMaterial = gaaMaterial;
       this.gaaAtivo = gaaAtivo;
       this.gaaVendasProdutoses = gaaVendasProdutoses;
    }
   
     @Id 

    
    @Column(name="gaa_idProdutos", unique=true, nullable=false)
    public int getGaaIdProdutos() {
        return this.gaaIdProdutos;
    }
    
    public void setGaaIdProdutos(int gaaIdProdutos) {
        this.gaaIdProdutos = gaaIdProdutos;
    }

    
    @Column(name="gaa_nome", nullable=false, length=50)
    public String getGaaNome() {
        return this.gaaNome;
    }
    
    public void setGaaNome(String gaaNome) {
        this.gaaNome = gaaNome;
    }

    
    @Column(name="gaa_descricao", nullable=false, length=65535)
    public String getGaaDescricao() {
        return this.gaaDescricao;
    }
    
    public void setGaaDescricao(String gaaDescricao) {
        this.gaaDescricao = gaaDescricao;
    }

    
    @Column(name="gaa_preco", nullable=false, precision=10)
    public BigDecimal getGaaPreco() {
        return this.gaaPreco;
    }
    
    public void setGaaPreco(BigDecimal gaaPreco) {
        this.gaaPreco = gaaPreco;
    }

    
    @Column(name="gaa_marca", nullable=false, length=30)
    public String getGaaMarca() {
        return this.gaaMarca;
    }
    
    public void setGaaMarca(String gaaMarca) {
        this.gaaMarca = gaaMarca;
    }

    
    @Column(name="gaa_material", nullable=false, length=50)
    public String getGaaMaterial() {
        return this.gaaMaterial;
    }
    
    public void setGaaMaterial(String gaaMaterial) {
        this.gaaMaterial = gaaMaterial;
    }

    
    @Column(name="gaa_ativo", nullable=false, length=1)
    public String getGaaAtivo() {
        return this.gaaAtivo;
    }
    
    public void setGaaAtivo(String gaaAtivo) {
        this.gaaAtivo = gaaAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gaaProdutos")
    public Set getGaaVendasProdutoses() {
        return this.gaaVendasProdutoses;
    }
    
    public void setGaaVendasProdutoses(Set gaaVendasProdutoses) {
        this.gaaVendasProdutoses = gaaVendasProdutoses;
    }




}


