package bean;
// Generated 13/10/2025 08:01:10 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GaaUsuarios generated by hbm2java
 */
@Entity
@Table(name="gaa_usuarios"
    ,catalog="db_gabriel_amaral"
)
public class GaaUsuarios  implements java.io.Serializable {


     private int gaaIdusuarios;
     private String gaaNome;
     private String gaaApelido;
     private String gaaCpf;
     private Date gaaDataNascimento;
     private String gaaSenha;
     private int gaaNivel;
     private String gaaAtivo;
     private Set gaaVendases = new HashSet(0);

    public GaaUsuarios() {
    }

	
    public GaaUsuarios(int gaaIdusuarios, String gaaNome, String gaaApelido, String gaaCpf, String gaaSenha, int gaaNivel, String gaaAtivo) {
        this.gaaIdusuarios = gaaIdusuarios;
        this.gaaNome = gaaNome;
        this.gaaApelido = gaaApelido;
        this.gaaCpf = gaaCpf;
        this.gaaSenha = gaaSenha;
        this.gaaNivel = gaaNivel;
        this.gaaAtivo = gaaAtivo;
    }
    public GaaUsuarios(int gaaIdusuarios, String gaaNome, String gaaApelido, String gaaCpf, Date gaaDataNascimento, String gaaSenha, int gaaNivel, String gaaAtivo, Set gaaVendases) {
       this.gaaIdusuarios = gaaIdusuarios;
       this.gaaNome = gaaNome;
       this.gaaApelido = gaaApelido;
       this.gaaCpf = gaaCpf;
       this.gaaDataNascimento = gaaDataNascimento;
       this.gaaSenha = gaaSenha;
       this.gaaNivel = gaaNivel;
       this.gaaAtivo = gaaAtivo;
       this.gaaVendases = gaaVendases;
    }
   
     @Id 

    
    @Column(name="gaa_idusuarios", unique=true, nullable=false)
    public int getGaaIdusuarios() {
        return this.gaaIdusuarios;
    }
    
    public void setGaaIdusuarios(int gaaIdusuarios) {
        this.gaaIdusuarios = gaaIdusuarios;
    }

    
    @Column(name="gaa_nome", nullable=false, length=50)
    public String getGaaNome() {
        return this.gaaNome;
    }
    
    public void setGaaNome(String gaaNome) {
        this.gaaNome = gaaNome;
    }

    
    @Column(name="gaa_apelido", nullable=false, length=25)
    public String getGaaApelido() {
        return this.gaaApelido;
    }
    
    public void setGaaApelido(String gaaApelido) {
        this.gaaApelido = gaaApelido;
    }

    
    @Column(name="gaa_cpf", nullable=false, length=14)
    public String getGaaCpf() {
        return this.gaaCpf;
    }
    
    public void setGaaCpf(String gaaCpf) {
        this.gaaCpf = gaaCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gaa_dataNascimento", length=10)
    public Date getGaaDataNascimento() {
        return this.gaaDataNascimento;
    }
    
    public void setGaaDataNascimento(Date gaaDataNascimento) {
        this.gaaDataNascimento = gaaDataNascimento;
    }

    
    @Column(name="gaa_senha", nullable=false, length=20)
    public String getGaaSenha() {
        return this.gaaSenha;
    }
    
    public void setGaaSenha(String gaaSenha) {
        this.gaaSenha = gaaSenha;
    }

    
    @Column(name="gaa_nivel", nullable=false)
    public int getGaaNivel() {
        return this.gaaNivel;
    }
    
    public void setGaaNivel(int gaaNivel) {
        this.gaaNivel = gaaNivel;
    }

    
    @Column(name="gaa_ativo", nullable=false, length=1)
    public String getGaaAtivo() {
        return this.gaaAtivo;
    }
    
    public void setGaaAtivo(String gaaAtivo) {
        this.gaaAtivo = gaaAtivo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="gaaUsuarios")
    public Set getGaaVendases() {
        return this.gaaVendases;
    }
    
    public void setGaaVendases(Set gaaVendases) {
        this.gaaVendases = gaaVendases;
    }




}


