package bean;
// Generated 13/10/2025 08:01:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * GaaVendedor generated by hbm2java
 */
@Entity
@Table(name="gaa_vendedor"
    ,catalog="db_gabriel_amaral"
)
public class GaaVendedor  implements java.io.Serializable {


     private int gaaIdVendedor;
     private String gaaNome;
     private String gaaTelefone;
     private String gaaCpf;
     private String gaaTurno;
     private BigDecimal gaaSalario;
     private String gaaEmail;

    public GaaVendedor() {
    }

    public GaaVendedor(int gaaIdVendedor, String gaaNome, String gaaTelefone, String gaaCpf, String gaaTurno, BigDecimal gaaSalario, String gaaEmail) {
       this.gaaIdVendedor = gaaIdVendedor;
       this.gaaNome = gaaNome;
       this.gaaTelefone = gaaTelefone;
       this.gaaCpf = gaaCpf;
       this.gaaTurno = gaaTurno;
       this.gaaSalario = gaaSalario;
       this.gaaEmail = gaaEmail;
    }
   
     @Id 

    
    @Column(name="gaa_idVendedor", unique=true, nullable=false)
    public int getGaaIdVendedor() {
        return this.gaaIdVendedor;
    }
    
    public void setGaaIdVendedor(int gaaIdVendedor) {
        this.gaaIdVendedor = gaaIdVendedor;
    }

    
    @Column(name="gaa_nome", nullable=false, length=50)
    public String getGaaNome() {
        return this.gaaNome;
    }
    
    public void setGaaNome(String gaaNome) {
        this.gaaNome = gaaNome;
    }

    
    @Column(name="gaa_telefone", nullable=false, length=11)
    public String getGaaTelefone() {
        return this.gaaTelefone;
    }
    
    public void setGaaTelefone(String gaaTelefone) {
        this.gaaTelefone = gaaTelefone;
    }

    
    @Column(name="gaa_cpf", nullable=false, length=14)
    public String getGaaCpf() {
        return this.gaaCpf;
    }
    
    public void setGaaCpf(String gaaCpf) {
        this.gaaCpf = gaaCpf;
    }

    
    @Column(name="gaa_turno", nullable=false, length=20)
    public String getGaaTurno() {
        return this.gaaTurno;
    }
    
    public void setGaaTurno(String gaaTurno) {
        this.gaaTurno = gaaTurno;
    }

    
    @Column(name="gaa_salario", nullable=false, precision=7)
    public BigDecimal getGaaSalario() {
        return this.gaaSalario;
    }
    
    public void setGaaSalario(BigDecimal gaaSalario) {
        this.gaaSalario = gaaSalario;
    }

    
    @Column(name="gaa_email", nullable=false, length=100)
    public String getGaaEmail() {
        return this.gaaEmail;
    }
    
    public void setGaaEmail(String gaaEmail) {
        this.gaaEmail = gaaEmail;
    }


     @Override
     public String toString(){
    return this.getGaaNome();
}

}


