package bean;
// Generated 13/10/2025 08:01:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GaaVendas generated by hbm2java
 */
@Entity
@Table(name="gaa_vendas"
    ,catalog="db_gabriel_amaral"
)
public class GaaVendas  implements java.io.Serializable {


     private int gaaIdVendas;
     private GaaClientes gaaClientes;
     private GaaVendedor gaaVendedor;
     private Date gaaDataVenda;
     private BigDecimal gaaTotal;
     private String gaaStatus;
     private String gaaMetodoPagamento;
     private Date gaaDataPagamento;
  

    public GaaVendas() {
    }

	
    public GaaVendas(int gaaIdVendas, BigDecimal gaaTotal, String gaaStatus, String gaaMetodoPagamento) {
        this.gaaIdVendas = gaaIdVendas;
        this.gaaTotal = gaaTotal;
        this.gaaStatus = gaaStatus;
        this.gaaMetodoPagamento = gaaMetodoPagamento;
    }
    public GaaVendas(int gaaIdVendas, GaaClientes gaaClientes, GaaVendedor gaaVendedor, Date gaaDataVenda, BigDecimal gaaTotal, String gaaStatus, String gaaMetodoPagamento, Date gaaDataPagamento) {
       this.gaaIdVendas = gaaIdVendas;
       this.gaaClientes = gaaClientes;
       this.gaaVendedor = gaaVendedor;
       this.gaaDataVenda = gaaDataVenda;
       this.gaaTotal = gaaTotal;
       this.gaaStatus = gaaStatus;
       this.gaaMetodoPagamento = gaaMetodoPagamento;
       this.gaaDataPagamento = gaaDataPagamento;
       
    }
   
     @Id 

    
    @Column(name="gaa_idVendas", unique=true, nullable=false)
    public int getGaaIdVendas() {
        return this.gaaIdVendas;
    }
    
    public void setGaaIdVendas(int gaaIdVendas) {
        this.gaaIdVendas = gaaIdVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gaa_idCliente")
    public GaaClientes getGaaClientes() {
        return this.gaaClientes;
    }
    
    public void setGaaClientes(GaaClientes gaaClientes) {
        this.gaaClientes = gaaClientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="gaa_idVendedor")
    public GaaVendedor getGaaVendedor() {
        return this.gaaVendedor;
    }
    
    public void setGaaUsuarios(GaaUsuarios gaaUsuarios) {
        this.gaaVendedor = gaaVendedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gaa_dataVenda", length=10)
    public Date getGaaDataVenda() {
        return this.gaaDataVenda;
    }
    
    public void setGaaDataVenda(Date gaaDataVenda) {
        this.gaaDataVenda = gaaDataVenda;
    }

    
    @Column(name="gaa_total", nullable=false, precision=10)
    public BigDecimal getGaaTotal() {
        return this.gaaTotal;
    }
    
    public void setGaaTotal(BigDecimal gaaTotal) {
        this.gaaTotal = gaaTotal;
    }

    
    @Column(name="gaa_status", nullable=false, length=20)
    public String getGaaStatus() {
        return this.gaaStatus;
    }
    
    public void setGaaStatus(String gaaStatus) {
        this.gaaStatus = gaaStatus;
    }

    
    @Column(name="gaa_metodoPagamento", nullable=false, length=20)
    public String getGaaMetodoPagamento() {
        return this.gaaMetodoPagamento;
    }
    
    public void setGaaMetodoPagamento(String gaaMetodoPagamento) {
        this.gaaMetodoPagamento = gaaMetodoPagamento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gaa_dataPagamento", length=10)
    public Date getGaaDataPagamento() {
        return this.gaaDataPagamento;
    }
    
    public void setGaaDataPagamento(Date gaaDataPagamento) {
        this.gaaDataPagamento = gaaDataPagamento;
    }





}


