package bean;
// Generated 13/10/2025 08:01:10 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * GaaVendasProdutos generated by hbm2java
 */
@Entity
@Table(name="gaa_vendas_produtos"
    ,catalog="db_gabriel_amaral"
)
public class GaaVendasProdutos  implements java.io.Serializable {


     private int gaaIdVendasProdutos;
     private GaaProdutos gaaProdutos;
     private GaaVendas gaaVendas;
     private int gaaQuantidade;
     private double gaaPrecoUnitario;
     private double gaaDesconto;
     private Date gaaDataEntrega;

    public GaaVendasProdutos() {
    }

	
    public GaaVendasProdutos(int gaaIdVendasProdutos, GaaProdutos gaaProdutos, GaaVendas gaaVendas, int gaaQuantidade, double gaaPrecoUnitario) {
        this.gaaIdVendasProdutos = gaaIdVendasProdutos;
        this.gaaProdutos = gaaProdutos;
        this.gaaVendas = gaaVendas;
        this.gaaQuantidade = gaaQuantidade;
        this.gaaPrecoUnitario = gaaPrecoUnitario;
    }
    public GaaVendasProdutos(int gaaIdVendasProdutos, GaaProdutos gaaProdutos, GaaVendas gaaVendas, int gaaQuantidade, double gaaPrecoUnitario, double gaaDesconto, Date gaaDataEntrega) {
       this.gaaIdVendasProdutos = gaaIdVendasProdutos;
       this.gaaProdutos = gaaProdutos;
       this.gaaVendas = gaaVendas;
       this.gaaQuantidade = gaaQuantidade;
       this.gaaPrecoUnitario = gaaPrecoUnitario;
       this.gaaDesconto = gaaDesconto;
       this.gaaDataEntrega = gaaDataEntrega;
    }
   
     @Id 

    
    @Column(name="gaa_idVendasProdutos", unique=true, nullable=false)
    public int getGaaIdVendasProdutos() {
        return this.gaaIdVendasProdutos;
    }
    
    public void setGaaIdVendasProdutos(int gaaIdVendasProdutos) {
        this.gaaIdVendasProdutos = gaaIdVendasProdutos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="gaa_idProduto", nullable=false)
    public GaaProdutos getGaaProdutos() {
        return this.gaaProdutos;
    }
    
    public void setGaaProdutos(GaaProdutos gaaProdutos) {
        this.gaaProdutos = gaaProdutos;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="gaa_idVenda", nullable=false)
    public GaaVendas getGaaVendas() {
        return this.gaaVendas;
    }
    
    public void setGaaVendas(GaaVendas gaaVendas) {
        this.gaaVendas = gaaVendas;
    }

    
    @Column(name="gaa_quantidade", nullable=false)
    public int getGaaQuantidade() {
        return this.gaaQuantidade;
    }
    
    public void setGaaQuantidade(int gaaQuantidade) {
        this.gaaQuantidade = gaaQuantidade;
    }

    
    @Column(name="gaa_precoUnitario", nullable=false, precision=10)
    public double getGaaPrecoUnitario() {
        return this.gaaPrecoUnitario;
    }
    
    public void setGaaPrecoUnitario(double gaaPrecoUnitario) {
        this.gaaPrecoUnitario = gaaPrecoUnitario;
    }

    
    @Column(name="gaa_desconto", precision=10)
    public double getGaaDesconto() {
        return this.gaaDesconto;
    }
    
    public void setGaaDesconto(double gaaDesconto) {
        this.gaaDesconto = gaaDesconto;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="gaa_dataEntrega", length=10)
    public Date getGaaDataEntrega() {
        return this.gaaDataEntrega;
    }
    
    public void setGaaDataEntrega(Date gaaDataEntrega) {
        this.gaaDataEntrega = gaaDataEntrega;
    }




}


